
#simple cpnfiguration for a mysql/maridb database
spring:
  application:
    name: e-bank-backend

  datasource:
    url: jdbc:mysql://localhost:3306/dbname
    username: dbusername
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver







  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect


server:
  port: 8080



